export interface IBudgetRegel {
    categorienaam: string,
    categorienummer: number,
    BudgetYear: string,
    isinkomsten: number,
    January: number,
    February: number,
    March: number,
    April: number,
    May: number,
    June: number,
    July: number,
    August: number,
    September: number,
    October: number,
    November: number,
    December: number,
    Total: number,
    Display:string
  }